### ISSUE TITLE
SERVICE clauses

### ISSUE THREAD

**Issue by dwhitney** [Tpt/rudf#8]
Hey, I've been playing with your library the past couple of days. It's really great - thanks for the work!

I'd like to use SERVICE clauses to fetch remote data. I realize that this is a large architectural change. Do you have any thoughts on what you'd like to do to make this work? I've been programming Rust for about a week, so I'm a bit out of my element, but I'm an experienced programmer. If you want to outline it, I could take a pass at implementing it.

Thanks!

**Comment by Tpt** [comment]
Hi! Thank you for using my project!

The SERVICE clause was not high in my priorities because I do not have much uses for it (I wanted to get SPARQL UPDATE and a lot of optimizations done before) so your help on this side is very welcome!

The SPARQL parser should already properly parse the SERVICE nodes and represent them in the `GraphPattern::Service` node of the SPARQL algebra AST.

The quick&dirty&slow way to implement the SERVICE evaluation without a big code refactoring would be to implement a synchronous SPARQL HTTP client that could make use of the existing XML SPARQL results parser.

Then, one could add a `Service` node to the `PlanNode` enum that store the optimized query plan and the conversion from `GraphPattern::Service` to `PlanNode::Service` in the `PlanBuilder`. The `PlanNode::Service` could keep its child query pattern as a `PlanNode` in order to still be able to serialize it back to SPARQL (it could be easily done by wrapping it into a `QueryVariants` that implements SPARQL serialization in the usual `std::fmt::Display` implementation.
This way the evaluator would just have to serialize the child `PlanNode` to SPARQL, use the client to get the results, encode and return them.

Then one could build optimization on top of it like bounding the child plan variables that could already be bound from other part of the query... But it's a further step.

Sorry, I am not sure that this explanation is very understandable. If it's unclear, feel free to ask further explanations. If you think of something better, please let me know (the approach I proposed seems the easiest to implement for me, but is probably also one of the slowest).

**Comment by dwhitney** [comment]
I plan to use this in a web browser via wasm, so I don't think a synchronous http request is an option since I can only do an async request. That said, I think what you've outlined is a good first step in getting familiar with the code. After that maybe coming up with an async implementation would be a good next step. I'll give it a try and see what I come up with. Thanks!

**Comment by dwhitney** [comment]
welp - I was wrong. You can make a synchronous http request: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests
Cool. I'll try this first.

**Comment by Tpt** [comment]
Great! It would be nice if the http client would work both on wasm and on regular targets. The very common [reqwest](https://github.com/seanmonstar/reqwest) library has now a wasm backend in its master branch and supports both sync and async. It might be a good tool to use.

**Comment by dwhitney** [comment]
I was thinking I'd just have an optional closure to handle services in the
`plan.eval` function with type `fn ((PatternVariable) -> Repository)` or
something like that. Then it would let the user supply their own method for
handling services. I think this would be preferable to adding an additional
http client as a dependency. Also I think having a http client baked in
would pose some difficulties if the user needed to configure the library
with different headers and things like that. I've got something kind of
working now. Hopefully I'll make a PR later today.

Thanks!

**Comment by Tpt** [comment]
It sounds like a good plan. Thank you!
A signature like `fn (NamedNode) -> Repository` or `fn (NamedNode) -> (fn(GraphPattern) ->  BindingsIterator)` might be even simpler to use.

**Comment by dwhitney** [comment]
This is what I've got right now:

```rust
pub struct SimpleEvaluator<S: StoreConnection> {
    dataset: DatasetView<S>,
    bnodes_map: Mutex<BTreeMap<u64, u128>>,
    base_iri: Option<Iri<String>>,
    now: DateTime<FixedOffset>,
    service_handler: Option<(fn(&PatternValue) -> Box<dyn Iterator<Item = Result<EncodedQuad>>>)>,
}
```

I wanted `Result<Repository>` instead of `Box<dyn Iterator<Item = Result<EncodedQuad>>>` but the compiler doesn't know the size of `Repository` at compile time, and I don't really know how to fix that :) Also I believe I will have to introduce a lifetime variable for the `Repository`, which I do understand, but it would be a large edit, so I'm just trying to get this working for now.

I feel the second type signature you recommend asks the library user to know a bit more about the internals of the plan evaluator that they should. But I'm also getting used to the library in general so, perhaps my intuition is off on that.

**Comment by dwhitney** [comment]
I'll push the code to my fork when I have a working test

**Comment by Tpt** [comment]
Nice! Thanks!

`Repository` is a trait so it does not have any size because it could be implemented multiple times.
This trait also covers a lot of features not needed here (quads insertions/deletions/file importation/...).

> I feel the second type signature you recommend asks the library user to know a bit more about the internals of the plan evaluator that they should. 

`NamedNode` and `BindingsIterator` are already part of the Rudf library public API, opposite to `PatternValue` and `EncodedQuad`. The later exposes details on how SPARQL queries are evaluated and how data are encoded internally.


It seems also that I might be misunderstanding something. Sorry for not having seen it earlier. The `SERVICE` clause is, following [the specification](https://www.w3.org/TR/sparql11-federated-query/) done to evaluate a part of the SPARQL query against a remote endpoint. [The `FROM` and `FROM NAMED` feature](https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#specifyingDataset) exists to allow to query remote files. Do you want to implement federated SPARQL (`SERVICE`) or beeing able to fetch remote RDF data (`FROM`)?

If we are in the first case, I am not sure to understand `fn(&PatternValue) -> Box<dyn Iterator<Item = Result<EncodedQuad>>>`. According [to the spec](https://www.w3.org/TR/sparql11-federated-query/), a federated processor takes a SPARQL query as input and returns a list of binding set. Here it seems to just return an iterator of quads.

If we are in the second case, I believe that we should use the `FROM` syntax for this feature as suggested by the specification. The `FROM` parameter values are stored in the `DatasetSpec` struct of the algebra AST. Implementing its evaluation should probably be quite easy to do by tweaking the `DatasetView` struct.

Sorry again for not having raised this concern earlier.

**Comment by dwhitney** [comment]
Ah ok. Yes I do think this is probably the best type then: `fn (NamedNode) -> (fn(GraphPattern) -> BindingsIterator)`. I'll try that

**Comment by dwhitney** [comment]
Hey I've almost got this working. One question for you. It looks like NamedNode has an iri_id that's a u128. How to I get the string value for that? I have been calling `dataset.get_str` but it keeps returning None - however when debugging, I can see that the values are inserted into the store. I must be doing something wrong. Can you point me at some code that resolves this for me? Thanks!

**Comment by dwhitney** [comment]
nevermind - I figured it out

**Comment by dwhitney** [comment]
alright it's nearly there. I need to join the bindings from the service clause with the rest of the data and support `SILENT`. You can have a look at some test code: https://github.com/dwhitney/rudf/blob/service-support/lib/tests/service_test_cases.rs

**Comment by dwhitney** [comment]
@Tpt wondering if you could help me out with the last step in this:

In the `streaming-support` branch of the fork I'm working in, the main entry point for  service support is [here](https://github.com/dwhitney/rudf/blob/service-support/lib/src/sparql/eval.rs#L208). It works except for when the `BindingIterator` returned from the from the service clause has different variables than the `EncodedTuplesIterator` that it needs to join with. When they are different, the result set of the join is a cartesian product. I can figure out how to fix this, but if you've already written some code to deal with this sort of thing, that'd be helpful. 

Thanks!

**Comment by Tpt** [comment]
Hi! Sorry for the late answer, I was attending a wedding this week-end. 

About joins, I believe you are looking for the `combine_tuples` method in the `eval` package that checks that two tuples are compatible and join them if they are. The `Service` evaluator should call it on the service results and the `from` parameter.

Some comments on your code.
1. You could avoid passing around `variables` in the `eval_plan` method by just storing them in the `PlanNode::Service` field like it is done for `PlanNode::Project`. You would also avoid to have to carefully convert it each time the recursive evaluation crosses a `Project` or an `Aggregate`.
2. Instead of passing the `ServiceHandler` to the `evaluate_select_plan` methods, I would add it as parameter to the `SimpleEvaluator::new` method and add it to the `SimpleEvaluator` struct. I believe it would make code nicer and simpler.
3. `vec![].into_iter()` could be nicely replaced by `empty()` (from `std::iter::`).
4. Please avoid `.unwrap()` except it is obvious that the code will never fail. I tried to make this library as resilient as possible by returning errors instead of panics.

**Comment by dwhitney** [comment]
I will look at `combine_tuples` - I assumed this was handled at some other point in the AST, but maybe not. 

As for your other comments - once I get this working I think I will probably make a new branch off master and rewrite it. This has been largely a Rust learning experience for me, and along the way I've realized that a lot of what I've done can be done much better. I really appreciate your feedback and patience!

**Comment by Tpt** [comment]
> I will look at combine_tuples - I assumed this was handled at some other point in the AST, but maybe not.

There is `PlanNode::Join` but I don't believe you have to directly deal with it for implementing services.

> As for your other comments - once I get this working I think I will probably make a new branch off master and rewrite it.

The code is already pretty good. What you might do is a squash to keep the history clean. I also learned Rust with this project (the code evolved quite a lot since the first commits).

**Comment by dwhitney** [comment]
Ok I've got it working! There are a couple of things to discuss with respect to your previous comment.

1. `variables` - up until now the way `eval_plan` works is you recusively traverse the AST out to the leaves and then return an `EncodedTuplesIterator`. When new variables are encountered, they are added to the end of the tuple. 

That changes a bit with the `SERVICE` clause because it's essentially a leaf in the sense that context is lost - you can't follow the typical pattern:

```rust
self.eval_plan(&*child, from, variables, service_handler).flat_map_ok(move |tuple| {...}
```
The above code would return an empty iterator. Instead you call `service_handler.handle`, which returns a `BindingsIterator`, which intern needs to be re-encoded into an `EncodedTuplesIterator`. Because the `BindingsIterator` may come back with new variables, you have to reconcile the order of those variables with the order currently in scope with `eval_plan`. For that reason, I believe the `variables` for the current context of `eval_plan` needs to be passed around. You suggested storing the variables in the `PlanNode::Service`. I guess this could be done at the parsing stage, but I don't really know how, and I'm not sure if it's practical.

I am a bit concerned about this because there are probably edge cases I'm not considering where the `variables` need to be updated. But maybe not? Also if you wanted to move away from iterators to streams, I'm not sure that order could be depended upon in the `EncodedTuplesIterator. I don't know enough about concurrency in Rust to know what issues there may be.

2. `ServiceHandler`

I don't really like the way I've implemented the `ServiceHandler` as a trait because if you do not wish to use a `ServiceHandler` and you call `prepared_query.exec(None)` where `None` is `Option<ServiceHandler>`, you get a compile error because the compiler doesn't know the type to associate with the function argument, so you either have to annotate the function, or supply an argument where the type can be determined. I created a ServiceHandler that does nothing called `NoneService` for this purpose, but this feels a hacky.

I think a better approach is to simply make the argument to `prepared_query.exec` a closure  instead of a trait. This should allow you to call `prepared_query.exec(None)` without any type annotations. Originally this is the method I wanted to try, but I had issues with lifetime values. I think now that I understand them a bit better I may be able to get around it. That said, this may necessitate threading `service_handler` to `eval_plan` all over the place unless I can add it to `SimpleEvaluator` - which is where I ran into the lifetime issues. I will try it and see how far I get.

In any case I appreciate your feedback and I'll integrate your recommendations before making a PR.

**Comment by dwhitney** [comment]
I had another look at this tonight. I think I see the variables you mentioned in plan_builder.rs. I'll take a look tomorrow.

Also I had a look at adding `service_handler` to `SimpleEvaluator` via `new`. If this is done, then you have to either add a new type variable to `SimpleEvaluator` that's either a lifetime variable or a normal type, depending on if you want to use HRTB. Either way, the variable threads itself all the way through the code base back to `Repository`. And once there, you end up with the type inference issue I mentioned in the previous comment. I really think the best way to handle this is to add a simple closure to the `PreparedQuery::exec` function. It does mean you have to thread `service_handler` through every call to `eval_plan`, but either way, you've got to thread something somewhere. This option seems better because it is encapsulated in the implementation, rather than adding extraneous type variables to the user.

Anyway, my PR should be ready tomorrow.

**Comment by Tpt** [comment]
Thank you for your detailed responses! Nice to hear your work should be ready soon!

> 1. variables
> I guess this could be done at the parsing stage, but I don't really know how, and I'm not sure if it's practical.

The recursive call `self.build_for_graph_pattern(child, variables, graph_name)` in the graph builder is going to fill all variables in the SERVICE into the `variables` `Vec`. This `vec` is built to give the encoding between the `Variable` objects and the position in the `EncodedTuple`. To avoid having to pass variables into the evaluator you just have to do the `build_for_graph_pattern` recursive call in the builder and, when retrieving the `BindingsIterator` during evaluation, to just use the `variables` `Vec` you would have cloned in `PlanNode::Service` to  properly do the conversion between `BindingsIterator` and `EncodedTuplesIterator`. If you prefer, you could keep your code as it is and I'll make a follow up pull request trying to implement this change.

> 2. `ServiceHandler`.

I believe that the trait is still cleaner because it makes the types clearer and makes creating `ServiceHandler` with states easier (e.g. to keep a connection pool). Indeed, passing None is not very ergonomic but I believe that `ServiceHander` is only going to be injected when you create a new `Repository` so it's not going to clutter the code much.

> Also I had a look at adding service_handler to SimpleEvaluator via new. 

Thank you for having a look at it! Don't bother with it, I'll have a look at it and try to make a follow up pull request if I find a way.

**Comment by dwhitney** [comment]
I think the type inference issue I've pointed out is worse than it may seem. You can't actually pass `None` to the `new` function. Because a trait is used, the compiler can't infer the type so you have to add a type annotation, like: 

```rust
let service_handler: Option<dyn ServiceHandler<'a>> = None;
let evaluator = SimpleEvaluator::new(... , service_handler));
```

If you couple that with the fact that using a trait requires threading a new type variable through pretty much every type in the library, I think a simple closure becomes more compelling. 

I've got both implemented in a couple of different branches. It would be easy for me to switch from on to the other, but I'll continue on the closure path for now.

**Comment by Tpt** [comment]
There is also the syntax:
```rust
let evaluator = SimpleEvaluator::new(... , None as Option<dyn ServiceHandler<'a>>));
```

> If you couple that with the fact that using a trait requires threading a new type variable through pretty much every type in the library, I think a simple closure becomes more compelling.

If the library user needs to give the `ServiceHandler` each time they want to execute a SPARQL query, we are probably not creating a nice API design. Imho the `ServiceHandler` should be given only once when creating the `Repository`. It's what is done in other RDF libraries like `rdf4j`.

**Comment by Tpt** [comment]
>  The closure in the exec function allow you to swap out ServiceHandlers without having to create a new Repository. 

Indeed. But I'm afraid of cluttering the API by adding extra parameters to the exec functions
I am also considering allowing to query the union of all named graphs as the default graph.

So, maybe we could add a `QueryOptions` parameter to the exec function that could contain the `ServiceHandler` and the option for "union as default". If you think it's a good idea, I could start a first version with "union as default" and then you could update it with the `ServiceHander`. What do you tihnk about it?

**Comment by dwhitney** [comment]
that sounds great! I also want to add support for custom functions like the
ones described here:
https://jena.apache.org/documentation/query/library-function.html and that
would also be a good place to add support

**Comment by Tpt** [comment]
Great! I'm currently writing the change.

**Comment by Tpt** [comment]
Done with #10 . What do you think about it?

Having support of custom functions (and maybe aggregates?) would be amazing.

**Comment by dwhitney** [comment]
Looks great! Ship it!
